services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: marksuser
      POSTGRES_PASSWORD: markspass
      POSTGRES_DB: marksdb
    volumes:
    # mount the init script
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    # the volume's name for persistent data
      - persist_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    # TODO: you will need to add to this
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=marksdb
      - DB_USER=markuser
      - DB_PASSWORD=markspass
    depends_on:
      - db

  frontend:
    # TODO: you will need to add to this
    build: ./frontend
    ports:
      -"8000:80"
    depends_on:
      - backend

  automark:
    build: ./automark
    depends_on:
      - backend
      - db
    profiles:
      - debug

volumes:
  persist_data: